force-app/main/default/objects/Account/recordTypes/Branch.recordType-meta.xml
<RecordType>
    <fullName>Branch</fullName>
    <active>true</active>
    <description>BetterBond Branch</description>
    <label>Branch</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>BetterBond Region</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Region_Suburb__c/Region_Suburb__c.object-meta.xml
<CustomObject>
    <label>Region - Suburb</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Region-Suburb Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region - Suburbs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region_Suburb__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>253</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region_Suburb__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <length>253</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region_Suburb__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>253</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region_Suburb__c/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <label>Suburb</label>
    <length>253</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SuburbRegionMapperControllerTest.cls
/**
 * Created by frans fourie on 2023/05/24.
 */

@IsTest
public with sharing class SuburbRegionMapperControllerTest {

    @TestSetup
    public static void createTestData(){
        Account region = new Account();
        region.Name = 'Region Account';
        region.RecordTypeId = [SELECT Id FROM RecordType WHERE Name LIKE '%region%'].Id;

        insert region;

        Account branch = new Account();
        branch.Name = 'Branch Account';
        branch.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'branch'].Id;
        branch.ParentId = region.Id;

        insert branch;

        Account subBranch = new Account();
        subBranch.Name = 'Suburb Account';
        subBranch.RecordTypeId = [SELECT Id FROM RecordType WHERE Name LIKE '%Sub-Branch%'].Id;
        subBranch.ParentId = branch.Id;

        insert subBranch;


        Region_Suburb__c rs = new Region_Suburb__c();
        rs.Region__c = 'Region Account';
        rs.Suburb__c = 'suburb';
        rs.City__c = 'city';
        rs.Province__c = 'province';

        insert rs;
    }

    @IsTest
    public static void runTests(){
        String province = SuburbRegionMapperController.getProvinces()[0];
        String city = SuburbRegionMapperController.getCities(province)[0];
        String suburb = SuburbRegionMapperController.getSuburbs(province,city)[0];
        String regionId = SuburbRegionMapperController.getRegionId(province,city,suburb);
        String regionId2 = SuburbRegionMapperController.getRegionId2([SELECT Id FROM Region_Suburb__c WHERE Suburb__c = 'suburb'].Id);
        Region_Suburb__c rs = SuburbRegionMapperController.getSuburbDetails([SELECT Id FROM Region_Suburb__c WHERE Suburb__c = 'suburb'].Id);
        List<Region_Suburb__c> rsList = SuburbRegionMapperController.getRegionSuburb([SELECT Id FROM Region_Suburb__c WHERE Suburb__c = 'suburb'].Id);
        System.assert(regionId != null);
    }
}