force-app/main/default/objects/BLG_Campaign__c/BLG_Campaign__c.object-meta.xml
<CustomObject>
    <label>Betterbond (BB) Campaign</label>
    <nameField>
        <label>Betterbond (BB) Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Betterbond (BB) Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLG_Campaign__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLG_Campaign__c/fields/Type_of_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Campaign__c</fullName>
    <label>Type of Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Smart Service</fullName>
            </value>
            <value>
                <fullName>Website/API</fullName>
            </value>
            <value>
                <fullName>Create lead/manual</fullName>
            </value>
            <value>
                <fullName>Website/URL</fullName>
            </value>
            <value>
                <fullName>Auto create</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLG_Workflow__c/fields/Close_off_Reason__c.field-meta.xml
<CustomField>
    <fullName>Close_off_Reason__c</fullName>
    <label>Close off Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profile created - No contact</fullName>
            </value>
            <value>
                <fullName>No PA consent received</fullName>
            </value>
            <value>
                <fullName>No PA documents received</fullName>
            </value>
            <value>
                <fullName>No Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General enquiry</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Not interested - not buying</fullName>
            </value>
            <value>
                <fullName>Not interested - poor service - Direct</fullName>
            </value>
            <value>
                <fullName>Not interested - poor service - Region</fullName>
            </value>
            <value>
                <fullName>Not interested - browsing</fullName>
            </value>
            <value>
                <fullName>Not interested - process</fullName>
            </value>
            <value>
                <fullName>Not interested - poor service - Insurance</fullName>
            </value>
            <value>
                <fullName>Not interested - renting</fullName>
            </value>
            <value>
                <fullName>Already submitted to bank(s)</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Submitted to another originator</fullName>
            </value>
            <value>
                <fullName>Dealing with another region</fullName>
            </value>
            <value>
                <fullName>Further loan - FNB</fullName>
            </value>
            <value>
                <fullName>Complaint - Insurance</fullName>
            </value>
            <value>
                <fullName>Complaint - POPI</fullName>
            </value>
            <value>
                <fullName>Complaint - Direct</fullName>
            </value>
            <value>
                <fullName>Complaint - Region</fullName>
            </value>
            <value>
                <fullName>Complaint - Other</fullName>
            </value>
            <value>
                <fullName>Transfer out - Head office</fullName>
            </value>
            <value>
                <fullName>Transfer out - Insurance</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - NW</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - SE</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - WC</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - KZN</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - PTA</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - FS</fullName>
            </value>
            <value>
                <fullName>Transfer out - Region - EC</fullName>
            </value>
            <value>
                <fullName>Transfer out - Developments</fullName>
            </value>
            <value>
                <fullName>PA Requested - awaiting consent</fullName>
            </value>
            <value>
                <fullName>No PA consent received</fullName>
            </value>
            <value>
                <fullName>Awaiting OTP</fullName>
            </value>
            <value>
                <fullName>No OTP Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Bond.recordType-meta.xml
<RecordType>
    <fullName>Bond</fullName>
    <active>true</active>
    <businessProcess>Bond Opportunity</businessProcess>
    <label>Bond Opportunity</label>
</RecordType>

force-app/main/default/classes/OppsAutoCloseOffBatchTest.cls
@IsTest
private class OppsAutoCloseOffBatchTest {
    @TestSetup
    static void setup() {
        BLG_Workflow__c blg = new BLG_Workflow__c();
        blg.Name = 'Pre-Approval Consent';
        blg.Close_off_Reason__c = 'No PA consent received';
        blg.Close_off_Days__c = 4;
        blg.Close_off_Contact_Attempts__c = 2;

        insert blg;

        BLG_Workflow__c blg2 = new BLG_Workflow__c();
        blg2.Name = 'Awaiting OTP';
        blg2.Close_off_Reason__c = 'No OTP Received';
        blg2.Auto_Close__c = true;
        blg2.Close_off_Days__c = 4;
        blg2.Close_off_Contact_Attempts__c = 2;

        insert blg2;

        BLG_Campaign__c blg3 = new BLG_Campaign__c();
        blg3.Type_of_Campaign__c = 'Create lead/manual';
        blg3.SLA__c = 12;

        insert blg3;

        Opportunity opp = new Opportunity();
        opp.CloseDate = Date.newInstance(2022, 2, 2);
        opp.StageName = 'Working';
        opp.Name = 'test123abc';
        opp.Contact_Attempts__c = 0;
        opp.Status__c = 'PA Requested - awaiting consent';
        opp.Assignment_DateTime__c = Datetime.now().addDays(-300);

        insert opp;

        Opportunity opp2 = new Opportunity();
        opp2.CloseDate = Date.newInstance(2022, 2, 2);
        opp2.StageName = 'Working (Bond)';
        opp2.Name = 'test123abc';
        opp2.Contact_Attempts__c = 67;
        opp2.General_Opportunity__c = opp.Id;
        opp2.Assignment_DateTime__c = Datetime.now().addDays(-300);
        opp2.Status__c = 'Awaiting OTP';

        insert opp2;
    }
    @IsTest
    static void test() {
        Test.startTest();
        OppsAutoCloseOffBatch uca = new OppsAutoCloseOffBatch();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
    }
}